info: saola_26_samples_mergedseq_generalpop_pop.info
outmain: "results_mergedseq"
scriptsdir: "scripts"
mask: /home/genis/saola/genome_masks/v2/saola_ref/all/beds/autosome_rep_het_dep_map.regions
chroms: /home/genis/saola/genome_masks/saola_ref/all/beds/saolaRefN_autosomal.list
ref: /jbod1/mikkel/projects/202103_saola/data/saolaRefN.fasta
params:
 angsd:
  minQ: 30
  minMapQ: 25
  rmtrans: 1
 pcangsd:
  e: 0
